# Intro Tutorial

Hello! Here are some intro to jupyter notebooks, packages, shell commands and pythons syntax that will help you out when begining research

# Jupyter Notebooks

Notebooks are a great way of running python code line by line.
In a notebook you can write code in python cells and notes in a markdown cell. 

#### ShortCuts in Notebooks

shift + return : runs cell


b : creates a cell below


a : creates a cell above 


dd: deletes a cell


m : creates a markdown cell


y : turns a cell into python 


! : creates line for terminal command


"#" : creates a comment in a python cell 


### Task: Make a cell blow this cell that runs python code, and run the cell below 

In [4]:
print("Hello World")

Hello World


# Intro To Python

Data types are an important way of 

Python has its own coperations. Here are most of them listed out. 

$ + $: addition

$ - $ : subtraction

$ * $: multiplication 

= :equals

/ : division

** : exponentiation

// : integer division

% : modulus (absolute value)

$+=$ : adds and gets equal to 

$-=$ : subtracts and gets equal to  

$*=$: multiplys and gets equal to  

$/=$: divides and gets equal to  

%= : modulus and gets equal to  

$**=$: and gets equal to  

$<=$: less than and  equal to 

$>=$: greater than and equal to  



In [5]:
#Example
a=5 

b=6

c= a**2 +b**2

print(c)

61


### Practice 

Make a code that emulates the equation below 

$ a = \sqrt{25 +78.50*5} $
<br>

$c= \frac{25}{7} * 3 $ #your answer should round to the nearest integer 
<br>

$ x= |(7^2 +8^4 )/ (14- 21)^{5/2}|$
<br>



## Arrays and Data Structures

Data is stored into spacific categories called Data Types:

* int: an integer
* float: a decimal
* string: a sequence of characters
* list: a set of elements, these elements can be inegers, floats, strings etc.

<bk>

* tuple : similar to a list, however once these variables are set they cannot be changed

<bk>

* bool: a boolian (true or false)

* array: a list of elements that you can conduct math on
* dictionaries: a key and lock system that sets one element in pairs

The type() function will let you know which cagetory a variable falls under


In [3]:
# Examples

a= 2

print("a:",a,type(a))

b= 7.658

print("b:",b,type(b))

c= "Word"

print("c:",c,type(c))

d= False

print("d:",d,type(d))

e = [a,b,c,d]

print("e:",e,type(e))

f= (a,b,[3,4,'6']) # tuples are cool but are rarely used becasue they can get confusing

print("f:",f,type(f))

g= {1: 'Welcome', 2: 'to', 3: 'Python'} # dictionaries are a little tricky, we will expand on this later

print("g:",g, type(g))

a: 2 <class 'int'>
b: 7.658 <class 'float'>
c: Word <class 'str'>
d: False <class 'bool'>
e: [2, 7.658, 'Word', False] <class 'list'>
f: (2, 7.658, [3, 4, '6']) <class 'tuple'>
g: {1: 'Welcome', 2: 'to', 3: 'Python'} <class 'dict'>


You can also change the type of a varaible with teh following commands

str() : switches varaible to a string
<br>
int() : converts to an integer
<br>
float() : converts to a float



In [2]:
#Example

a= 6

a="7" # overwrites the first varaible

print(a, type(a))

a= int(a) # overwirtes it again and converts to an int

print(a, type(a))

a=float(a) #changes the variable to a float

print(a, type(a))

7 <class 'str'>
7 <class 'int'>
7.0 <class 'float'>


### Practice 

Create a string, int and float.Then turn the float into an integer.

## Arrays 
<br>
Arrays are a special data structure because you can perform mathematical operations efficiently on/with them. Unlike lists, the elements of an array must be numbers (integers or floats).

In [6]:
import numpy as np # this package is used for numeric operations on variables and arrays - arrays are faster because they vectorize calculations


# Creates a 1D array with the values listed above (ranging from 1-6)
a = np.array([6,3,7,450,9,2,65,89,10,1])

# arange: Returns evenly spaced values within a given interval.
b = np.arange(10,20,2)  # (start, stop, step) --> stop is not inclusive, ie. 20 will NOT be included in array here

# linspace: Returns evenly spaced numbers over a specified interval.
c = np.linspace(50,100,6) # (start, stop, number_of_samples_to_generate) --> confusingly, the stop here IS inclusive ie. 100 WILL be included in array

# zeros: Returns a new array of given shape and type, filled with zeros.
d = np.zeros(2)
print(a, "\n", b, "\n", c, "\n", d)

[  6   3   7 450   9   2  65  89  10   1] 
 [10 12 14 16 18] 
 [ 50.  60.  70.  80.  90. 100.] 
 [0. 0.]


#### Array come in all shapes and sizes

In [7]:
# Get array shape
print('Shape',a.shape) # (n,) tells us this is a 1D array with 6 elements

print("Size",a.size)  # tells us the number of elements - can also use: len(a) , which will work for lists

#a=a.sort # You can also sort or reshape an array that does from lowest to highest
print("Sorted",np.sort(a))

print('Reshaped',"\n",a.reshape(5,2)) #reshape the arry to 2 columns and 5 rows

a.flatten #will flatten the array to be back to 1D
print("Flattened", a.flatten())

Shape (10,)
Size 10
Sorted [  1   2   3   6   7   9  10  65  89 450]
Reshaped 
 [[  6   3]
 [  7 450]
 [  9   2]
 [ 65  89]
 [ 10   1]]
Flattened [  6   3   7 450   9   2  65  89  10   1]


### Practice

a) Create a numpy array that ranges from 0 to 100 and skips every 2 integers

b) Create a numpy array that ranges from 0 to 100 with 500 steps

c) Crete a numpy array that is composed of 250 zeros

d) Create a numpy array with your choise of 7 values

e) Sort the array

### Slicing arrays

Sometimes you only want one value or a subset of values from an array. To do this you can slice it.

In [14]:
a = np.array([6,3,7,450,9,2,65,89,10,1])

In [15]:
# Slicing a Numpy array requires using [] brackets
a[0]  # Recall Python indexing, index [0] is the first element in your array

6

In [16]:
# Last element of an array can be indexed by using [-1], and using [-2] will give second last element, and so on
a[-1]

1

In [17]:
# Slicing parts of an array --> the ":" indicates to "pass all the way until the end"
sliced_a = a[2:]    # ie. all values after the 3rd element (corresponding to index 2) will be sliced into your new array
sliced_a

array([  7, 450,   9,   2,  65,  89,  10,   1])

In [18]:
# You can slice the array from beginning up to a certain index
a[:-2]

array([  6,   3,   7, 450,   9,   2,  65,  89])

In [19]:
a[:7] #up to but not including element 7

array([  6,   3,   7, 450,   9,   2,  65])

In [20]:
# Slice array in steps (here you are slicing by 2 steps), the "::" is so that the entire array is indexed this way
a[::2]

array([ 6,  7,  9, 65, 10])

In [ ]:
# you can also slice n by m arrays

b= np.array([[1,2,3,4,5],[6,7,8,9,10]]) #this creates an array with two rows and 5 columns
print(b)
print("shape",b.shape) #recall that arrays can have multiple shapes

print("First Row",b[0,:]) #will slice the array to give our first row
print("First Column",b[:,0]) #will slice to give our first column

#if you want a specific element, you need to give it the row and colum value much like an (x,y) ordered pair
print(b[0,2])



### Practice

Create a 2, by 3 array, check the shape and print the terms. Then reshape the array to be 3 by 2. Laslt flattent the array.

# If statments
An if stamtnets checks for a condition before running a block of code. If the statment is true the block of code will run, if it is false then the next block of code will run. 

In [22]:
# Example 1

a=9 #in an if statement you must first initialize the varaible becasue

if a<10 :  #our if condition checkt to see if a is less than  10
    print("a is less than 10")

else:#this else statment will appear if the condition is false 
    print("a is grater than or equal to 10")
    
#try to change a 

0


### Practice 

a) Write a code that determines weatehr a number is even or odd.
<br>

b) Write a code to determine if a number is prime

# Intro to Loops

In python to do an iritive process you use a loop. This can be done with a 'for' loop or a 'while' loop. 

* 'for' loops will repeate a block of code a known number of time
* 'while' loops will repeat a block of code while a condition is met


In [5]:
#Example of For loop        
x=0 

for x in range (10): 
    print(x)

0
1
2
3
4
5
6
7
8
9


In [4]:
y=0
while y<= 10:
    
    y= y+1
    
    print(y)


1
2
3
4
5
6
7
8
9
10
11


As you can see for a while loop one more itiration is done than the for loop. This is becasue the condition of being less than or equal to 10 is no longer met. 

* Notice if you did not add 1 to y, the code would run infinitly 

In [ ]:
#Practice
Create a code that will loop through an equation of your choosing before it hits some maximum value. 


# Functions 

A fucntion is a program that will conduct a peice of doce when you call on it. For example the print command is a function. Functions are called and use a paratheses to enter values.

* def : is the comand to define a function 
* functions take in one or more inputs
* a defintes input has a value already and does not need to 

In [1]:
# Example 
def my_subtraction_function(argument_1, argument_2 = 3):
  """
  The triple quotation marks are known as a doc string and are used to explain/document what the function does, what the inputs and outputs are.
  Function that takes the difference of argument 1 and argument 2.

  Input:
  argument_1 (int): first user input.
  argument_2 (int): second user input. Note that this argument is set to 3 when we define the function. This means that the argument has
                    a "fallback value" set to 3, so that if the user does not input a value for argument_2 when calling the function, the value
                    will automatically default to a value of 3. Conversely, the user can use any value other than 3 and the function will execute
                    using that value, as long as the value is of the same data type.

  Returns:
  solution (int): the sum of argument_1 and argument_2.
  """
  solution= argument_1 - argument_2

  return solution # this return statment will allow you to access this varaible in

# You typically want to save the output of a function call
my_difference = my_subtraction_function(argument_1 = 10)

my_difference

7

In [2]:
# To show that you can use both arguments when calling the function as well
my_subtraction_function(argument_1 = 10, argument_2 = 5)

5

In [3]:
# Function arguments keep their order, so you don't need to write "argument = " everytime. If you have a function with many arguments, it helps to type them out.
my_subtraction_function(5, 10)

-5

### Practice

Write a function that computes the quadratic formula. 

$  \frac {-b \pm \sqrt{(b^2 - 4ac) }}{2a}$

# 